#!/bin/bash

set -e

# Specify version
NERDCTL_VERSION="1.7.5"

echo "📥 Downloading nerdctl v${NERDCTL_VERSION}..."
curl -LO https://github.com/containerd/nerdctl/releases/download/v${NERDCTL_VERSION}/nerdctl-${NERDCTL_VERSION}-linux-amd64.tar.gz

echo "📦 Extracting..."
tar -xzf nerdctl-${NERDCTL_VERSION}-linux-amd64.tar.gz

echo "🚚 Moving binary to /usr/local/bin..."
sudo mv nerdctl /usr/local/bin/

echo "🧹 Cleaning up..."
rm nerdctl-${NERDCTL_VERSION}-linux-amd64.tar.gz

echo "✅ nerdctl installed!"
nerdctl --version
